language: rust
rust:
  - stable
  - nightly
jobs:
  allow_failures:
    - rust: nightly
  fast_finish: true
cache: cargo
install:
  - rustup component add clippy
  - apt-get install -y protobuf-compiler
script:
  - RUSTFLAGS=-Dwarnings cargo clippy
  - cargo test --verbose